### ISSUE TITLE
Integração do JSON resultande do Back-End com Interface Front-End

### ISSUE THREAD

**Issue by vitoriaguidines** [vitoriaguidines/app-de-carona#9]
Leitura dos atributos de saída da API em JSON relacionadas ao mapa com a interface Front-End

**Comment by CaioM29** [comment]
Criar e alterar endpoints para fazer a integração das rotas no frontend

**Comment by vitoriaguidines** [comment]
Mudança interface de Buscar:
- Mudar botão de pedir carona para uma interface com um botão só "escolher rota", mas ainda com informações como data, hora e quantidade de pessoas.
- Clica em Escolher Rota e é encaminhado para um mapa com duas barras para digitar endereço de origem e destino e apareceria a rota no mapa.
- Embaixo do mapa, assim que for exibida a rota, aparecerá um botão de confirmar rota.

**Comment by CaioM29** [comment]
Feito:

*  Mudar botão de pedir carona para uma interface com um botão só "escolher rota", mas ainda com informações como data, hora e quantidade de pessoas.
* Clica em Escolher Rota e é encaminhado para um mapa com duas barras para digitar endereço de origem e destino e apareceria a rota no mapa.

Deletado a página de mapaDestino;
Setada API-Key do google maps;
Colocado autocomplete para o endereço de ida e volta;
Calculo da rota origem -> destino baseado nos endereços;
Mostrar visualmente a rota selecionada no mapa;

**Comment by CaioM29** [comment]
Feito:

Mudar botão de pedir carona para uma interface com um botão só "escolher rota", mas ainda com informações como data, hora e quantidade de pessoas.

Clica em Escolher Rota e é encaminhado para um mapa com duas barras para digitar endereço de origem e destino e apareceria a rota no mapa.

**Comment by vitoriaguidines** [comment]
Tarefas finalizadas
